name: <NAME>
device: "cuda:1"
audio:
  min_duration: 2.0 #sec
  max_duration: 10.0 #sec
data:
  main_dir: "data/<NAME>/xtts" #путь до файлов обучения (wav/, train.txt, val.txt)
  base_wav_path: <PASTE_PATH> #аудио для обучения до разбиения
  weights_folder: "out/<NAME>/xtts" #путь до папки сохранения обученных весов
  checkpoint_path: null
  reference_audio: <PASTE_PATH>
models:
  whisper: "large-v3"
train:
  epochs: 15
  batch_size: 2