name: divertito
device: "cuda:1"
audio:
  min_duration: 2.0 #sec
  max_duration: 10.0 #sec
data:
  main_dir: "data/divertito/xtts" #путь до файлов обучения (wav/, train.txt, val.txt)
  base_wav_path: "" #аудио для обучения до разбиения
  weights_folder: "out/divertito/xtts"
  checkpoint_path: ""
  reference_audio: []
models:
  whisper: "large-v3"
  VAD_folder: models/VAD
train:
  epochs: 15
  batch_size: 2