name: shtefanov
device: cuda:0
audio:
  min_duration: 2.0
  max_duration: 10.0
data:
  main_dir: data/shtefanov/xtts
  base_wav_path: ""
  weights_folder: out/shtefanov/xtts
  checkpoint_path: ""
  reference_audio: []
models:
  whisper: large-v3
  VAD_folder: models/VAD
train:
  epochs: 20
  batch_size: 2
